config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  resources :philosophers
  resources :topics
  resources :materials
  resources :password_resets
  resources :users, :only => [:new, :create, :edit]

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/controllers/session_controller.rb
# class SessionController < ApplicationController
#   def new
#   end

#   def create
#     user = User.find_by :email => params[:email]
#     if user.present? && user.authenticate(params[:password])
#       session[:user_id] = user.id
#       redirect_to root_path
#     else 
#       redirect_to login_path
#     end
#   end

#   def destroy
#     session[:user_id] = nil
#     redirect_to login_path
#   end

# end

class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      if params[:remember_me]
        cookies.permanent[:auth_token] = user.auth_token
      else
        cookies[:auth_token] = user.auth_token
      end
      redirect_to root_path
    else 
      redirect_to login_path
    end
  end

  def destroy
    cookies.delete(:auth_token)
    redirect_to login_path, :notice => "Successfully logged out!"
  end

end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/session/new.html.erb
<h2>Log In</h2>
<br><br><br>
<body class="universal">


<%= form_tag login_path do %>

<div class="form">
    <%= email_field_tag :email, nil, :type => "text", :id => "email", :class => "form__input"%>
    <%= label_tag :email, nil, :for => "email", :class => "form__label"  %>
</div>

<br>

<div class="form">
    <%= password_field_tag :password, nil, :type => "text", :id => "email", :class => "form__input" %>
    <%= label_tag :password, nil, :for => "password", :class => "form__label" %>
</div>

<br>

<div class="btn-new">
<%= submit_tag "Sign in!" %>
</div>

<% end %>

<br>

<div class="btn-new">
    <%= label_tag :remember_me, "Keep me logged in!" %>
    <br>
    <%= check_box_tag :password, 1, params[:remember_me] %>
</div>

<br>

<h4>Reset password</h4>

<h5 class="body">
    <%= link_to "Forgot your password?", new_password_reset_url %>
</h5>

<br><br><br><br>

</body>