config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  resources :philosophers
  resources :topics
  resources :materials
  resources :password_resets
  resources :users, :only => [:new, :create, :edit]

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/philosopher.rb
class Philosopher < ApplicationRecord
    has_and_belongs_to_many :schools
    has_and_belongs_to_many :topics
    has_many :materials
end

app/controllers/philosophers_controller.rb
class PhilosophersController < ApplicationController
  before_action :check_for_login

  def index
    @philosophers = Philosopher.all
  end

  def show
    @philosopher = Philosopher.find(params[:id])
  end

  def new
    @philosopher = Philosopher.new
  end

  def create
    philosopher = Philosopher.create philosopher_params
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      philosopher.image = req["public_id"]
    end
    philosopher.update_attributes(philosopher_params)
    # philosopher.save
    redirect_to philosopher_path(philosopher)
  end


  def edit
    @philosopher = Philosopher.find(params[:id])
  end

  def update
    philosopher = Philosopher.find(params[:id])
      if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      philosopher.image = req["public_id"]
      end
      philosopher.update_attributes(philosopher_params)
      philosopher.save
      redirect_to philosopher_path
  end

  def destroy
    Philosopher.find(params[:id]).destroy
    redirect_to philosophers_path
  end

  private
  def philosopher_params
    params.require(:philosopher).permit(:title, :image)
  end
end

app/helpers/philosophers_helper.rb
module PhilosophersHelper
end

app/views/philosophers/edit.html.erb
<h1>Edit philosopher</h1>

<br><br><br>
<body class="universal">
    
<div class="form">
<%= form_for(@philosopher) do |f|%> <!--, :html => {:multipart => true}) -->
    <%= f.text_field :title, :required => true, :type => "text", :id => "email", :class => "form__input" %>
    <%= f.label "philosopher Name: ", :class => "form__label" %>
    
</div>
<br><br>

<div class="form">
    
    <%= f.text_field :bio, :required => true, :id => "email", :class => "form__input", :type => "text" %>
    <%= f.label "Philosopher bio:", :for => "email", :class => "form__label"   %>
</div>

<br><br>
<div class="form">
    <%= f.submit "Edit philosopher"%>
</div>
<% end %>

</body>

app/views/philosophers/index.html.erb
<h1>All philosophers</h1>

</div>

<h2 class="body">

<% @philosophers.each do |philosopher| %>
    <%= link_to philosopher.title, philosopher %>
<% end %>

</h2>

<%# #@philosophers.each do |philosopher|%>
    <%# #link_to(philosopher.title, philosopher) %>
<%# end %>

app/views/philosophers/new.html.erb
<h1>New philosopher</h1>
<br><br><br><br>
<body class="universal">

<div class="form">
<%= form_for(@philosopher, :html => {:multipart => true}) do |f|%>
    <%= f.label "Philosopher name:", :for => "email", :class => "form__label"   %>
    <%= f.text_field :title, :required => true, :id => "email", :class => "form__input", :type => "text"  %>
</div>



<h5 class="form">
    <%= f.submit %>
</h5>

    <% end %>

</body>

app/views/philosophers/show.html.erb
<h1>Materials on: <%= @philosopher.title %> </h1>

 <!--cl_image_tag(@philosopher.image)-->
</h2>
 <h2 class="body">
    <% if @philosopher.materials.present? %>
    <% @philosopher.materials.each do |material| %>
        <ul>Title: <%= link_to material.title, material %></ul>
        <ul>Author: <%= link_to material.author, material %></ul>
        <% end %>
    <% end %>
</h2>
<br>
<br>
<br>
<br>
<br>

<h2 class="body">

<% if @current_user.admin? %>
    <div class = "controls">
    <%= link_to 'Edit philosopher', edit_philosopher_path(@philosopher) %>
    <%= link_to 'Delete philosopher', @philosopher, :method => 'delete', :data => { :confirm => 'Are you super, super sure?' } %>
    </div>
<% end %>

    
</h2>