config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  resources :philosophers
  resources :topics
  resources :materials
  resources :password_resets
  resources :users, :only => [:new, :create, :edit]

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/material.rb
class Material < ApplicationRecord
    belongs_to :philosopher, :optional => true
    belongs_to :topic, :optional => true

    # TOPIC_LIST = ["Existentialism", "Language and Meaning", "Power and Knowledge", "Feminism", "Post-Colonial Theory", "Ethics", "Work and Value", "Virtue and Capitalism", "Consciousness", "Responsibility", "Emotion"]
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :check_for_login
  
  def index
    @materials = Material.all
  end

  def show
    @material = Material.find(params[:id])
  end

  def new
    @material = Material.new
  end

  def create
    material = Material.create material_params
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      material.image = req["public_id"]
    end
    material.update_attributes(material_params)
    # material.save
    redirect_to material_path(material)
  end

  def edit
    @material = Material.find(params[:id])
  end

  def update
    material = Material.find(params[:id])
      if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      material.image = req["public_id"]
      end
      material.update_attributes(material_params)
      material.save
      redirect_to material_path
  end

  def destroy
    material[:material_id] = nil
    redirect_to login_path
  end

  private
  def material_params
    params.require(:material).permit(:title, :author, :link, :topic_id)
  end
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/views/materials/edit.html.erb
<h1>Edit material</h1>

<br><br><br>
<body class="universal">
    
<div class="form">
<%= form_for(@material) do |f|%> <!--, :html => {:multipart => true}) -->
    <%= f.label "material Name: ", :for => "email", :class => "form__label" %>
    <%= f.text_field :title, :required => true, :id => "email", :class => "form__input", :type => "text" %>
</div>

<div class="form">
    <%= f.submit "Edit material"%>
</div>
<% end %>

</body>

app/views/materials/index.html.erb
<h1>All materials</h1>

<h2 class="body">

    <% @materials.each do |material|%>
        <%= link_to material.title, material %>
        
    <% end %>
    
    <br>

    <%= link_to 'Add new material', new_material_path(@material) %>

</h2>

app/views/materials/new.html.erb
<h1>New material</h1>
<br><br><br><br>

<body class="universal">

<%= form_for(@material, :html => {:multipart => true}) do |f|%>

<div class="form">
    
    <%= f.text_field :title, :required => true, :type => "text", :id => "email", :class => "form__input"  %>
    <%= f.label "Material name:", :class => "form__label"    %>
</div>

<br>

<div class="form">
    <%= f.text_field :author, :required => true, :id => "email", :class => "form__input", :type => "text" %>
    <%= f.label "Material author:", :for => "email", :class => "form__label"   %>
    
</div>

<br>

<div class="form">
    
    <%= f.url_field :link, :required => true, :id => "email", :class => "form__input", :type => "text"  %>
    <%= f.label "Link to material:", :for => "email", :class => "form__label"   %>
</div>

<br>

<div class="form">
    <%= f.label :topic_id %>
    <%= f.select(:topic_id, Topic.pluck(:title, :id), :include_blank => true)%>
</div> 

<h5 class="form">
    <%= f.submit %>
</h5>

<% end %>


</body>

app/views/materials/show.html.erb
<h1><%= @material.title %> by <%= @material.author %></h1>

<h2 class="body">

<%= link_to "#{@material.title}", @material.link %>

</h2>