config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  resources :philosophers
  resources :topics
  resources :materials
  resources :password_resets
  resources :users, :only => [:new, :create, :edit]

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user, :optional => true
end

app/models/material.rb
class Material < ApplicationRecord
    belongs_to :philosopher, :optional => true
    belongs_to :topic, :optional => true

    # TOPIC_LIST = ["Existentialism", "Language and Meaning", "Power and Knowledge", "Feminism", "Post-Colonial Theory", "Ethics", "Work and Value", "Virtue and Capitalism", "Consciousness", "Responsibility", "Emotion"]
end

app/models/philosopher.rb
class Philosopher < ApplicationRecord
    has_and_belongs_to_many :schools
    has_and_belongs_to_many :topics
    has_many :materials
end

app/models/school.rb
class School < ApplicationRecord
    has_and_belongs_to_many :philosophers
    has_many :topics
end

app/models/topic.rb
class Topic < ApplicationRecord
    has_and_belongs_to_many :philosophers
    has_many :materials
    belongs_to :school, :optional => true
end

app/models/user.rb
# class User < ApplicationRecord
#     validates :email, :presence => true, uniqueness: true
#     has_secure_password
#     has_many :comments
# end

class User < ApplicationRecord
    validates :email, :presence => true, uniqueness: true
    has_secure_password
    has_many :comments
    before_create { generate_token(:auth_token) }

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    PasswordMailer.password_reset(self).deliver
  end

    def generate_token(column)
        begin 
          self[column] = SecureRandom.urlsafe_base64
        end while User.exists?(column => self[column])
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :fetch_user
    
    private 
    
    def check_for_admin
        redirect_to login_path unless(@current_user.present? && @current_user.admin?)
    end

    # def fetch_user
    #     @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
    #     session[:user_id] = nil unless @current_user.present? #logout non-existent users
    # end

    def fetch_user
        @current_user = User.find_by_auth_token!(cookies[:auth_token]) if cookies[:auth_token].present?
    end

    def check_for_login
        redirect_to login_path unless @current_user.present?
    end

end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :check_for_login
  
  def index
    @materials = Material.all
  end

  def show
    @material = Material.find(params[:id])
  end

  def new
    @material = Material.new
  end

  def create
    material = Material.create material_params
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      material.image = req["public_id"]
    end
    material.update_attributes(material_params)
    # material.save
    redirect_to material_path(material)
  end

  def edit
    @material = Material.find(params[:id])
  end

  def update
    material = Material.find(params[:id])
      if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      material.image = req["public_id"]
      end
      material.update_attributes(material_params)
      material.save
      redirect_to material_path
  end

  def destroy
    material[:material_id] = nil
    redirect_to login_path
  end

  private
  def material_params
    params.require(:material).permit(:title, :author, :link, :topic_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/session_controller.rb
# class SessionController < ApplicationController
#   def new
#   end

#   def create
#     user = User.find_by :email => params[:email]
#     if user.present? && user.authenticate(params[:password])
#       session[:user_id] = user.id
#       redirect_to root_path
#     else 
#       redirect_to login_path
#     end
#   end

#   def destroy
#     session[:user_id] = nil
#     redirect_to login_path
#   end

# end

class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      if params[:remember_me]
        cookies.permanent[:auth_token] = user.auth_token
      else
        cookies[:auth_token] = user.auth_token
      end
      redirect_to root_path
    else 
      redirect_to login_path
    end
  end

  def destroy
    cookies.delete(:auth_token)
    redirect_to login_path, :notice => "Successfully logged out!"
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :check_for_login
  
    def index
      @topics = Topic.all
    end
  
    def show
      @topic = Topic.find params[:id]
    end
  
    def new
      @topic = Topic.new
    end
  
    def create
      topic = Topic.new topic_params
      if params[:file].present?
        req = Cloudinary::Uploader.upload(params[:file])
        topic.image = req["public_id"]
      end
      topic.update_attributes(topic_params)
      topic.save
      redirect_to topic_path(topic)
    end
  
  
    def edit
      @topic = Topic.find(params[:id])
    end
  
    def update
      topic = Topic.find(params[:id])
        if params[:file].present?
        req = Cloudinary::Uploader.upload(params[:file])
        topic.image = req["public_id"]
        end
        topic.update_attributes(topic_params)
        topic.save
        redirect_to topic_path
    end
  
    private
    def topic_params
      params.require(:topic).permit(:name)
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_login, :check_for_admin, except: [:new, :create]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/philosophers_helper.rb
module PhilosophersHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100&display=swap" rel="stylesheet">

    <title>Philosophy Cloud</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# cloudinary_js_config %>

  </head>

  <body>

  <div>

    <nav>

        <div class="logo">
          <h3><%= link_to "Philosophy Cloud", root_path, :class => "logo-btn" %></h3>
        </div>


        <div>

            <% if @current_user.present? %>
            
            <%= link_to "Materials", materials_path, :class => "btn"%>
            <%= link_to "Topics", topics_path, :class => "btn"%>
            <%= link_to "Philosophers", philosophers_path, :class => "btn"%>
            <%= link_to "Sign out #{ @current_user.email }", login_path, method: 'delete', :class => "btn"%>
    
          <% else%>
            
            <%= link_to "Sign up", new_user_path, :class => "btn"%>
            <%= link_to "Sign in", login_path, :class => "btn"%>

          <% end %>

        </div>

        <div class="nav-button">
          <div class="line1"></div>
          <div class="line2"></div>
          <div class="line3"></div>
        
        </div>
    
    </nav>

    

  <%= yield %>
  <%= javascript_include_tag 'application' %>

  </body>
<b></b><b></b><b></b><b></b><b></b>
    <footer>
    <p class="notice"><%= flash[:notice] %></p>
    <p class="alert"><%= flash[:alert] %></p>
    </footer>

</html>

app/views/layouts/index.html.erb
<h1>All users</h1>

<% @users.each do |user| %>

<p><%= user.email %></p>

<% end %>

app/views/pages/home.html.erb
<div class="brainContainer"></div>